# Generated by Django 2.0.6 on 2019-06-17 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartrest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Importo', models.FloatField()),
                ('Ditta', models.CharField(max_length=100)),
                ('Direttore', models.CharField(max_length=100)),
                ('Utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lavoro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codice_Tariffa', models.CharField(max_length=50)),
                ('Nome', models.CharField(max_length=100)),
                ('Importo', models.FloatField()),
                ('Costo_Unitario', models.FloatField(default=0.0)),
                ('Contratto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartrest.Contratto')),
            ],
        ),
        migrations.CreateModel(
            name='Misure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codice_Tariffa', models.CharField(max_length=50)),
                ('Data', models.DateField()),
                ('Designazione_Lavori', models.TextField(max_length=1000)),
                ('Parti_Uguali', models.IntegerField()),
                ('Larghezza', models.FloatField()),
                ('Lunghezza', models.FloatField()),
                ('Altezza_Peso', models.FloatField()),
                ('Positivi', models.IntegerField(max_length=10)),
                ('Negativi', models.CharField(max_length=10)),
                ('Riserva', models.BooleanField()),
                ('Annotazioni', models.CharField(max_length=1000)),
                ('Stato', models.TextField(choices=[('INSERITO_LIBRETTO', 'Inserita nel Libretto'), ('INSERITO_LIBRETTO_RISERVA', 'Inserita nel Libretto con Riserva'), ('CONFERMATO_LIBRETTO', 'Confermata nel Libretto'), ('CONFERMATO_REGISTRO', 'Confermata nel Registro di Contabilità')], default='INSERITO_LIBRETTO', max_length=100)),
                ('Lavoro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartrest.Lavoro')),
            ],
        ),
    ]
