# Generated by Django 2.0.6 on 2019-07-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrest', '0003_auto_20190723_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misura',
            name='Annotazioni',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='misura',
            name='Negativi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='misura',
            name='Riserva',
            field=models.CharField(choices=[('NO', 'No'), ('Si', 'Si')], max_length=10),
        ),
        migrations.AlterField(
            model_name='misura',
            name='Stato',
            field=models.CharField(choices=[('INSERITO_LIBRETTO', 'Inserita nel Libretto'), ('INSERITO_LIBRETTO_RISERVA', 'Inserita nel Libretto con Riserva'), ('CONFERMATO_LIBRETTO', 'Confermata nel Libretto'), ('CONFERMATO_REGISTRO', 'Confermata nel Registro di Contabilità')], default='INSERITO_LIBRETTO', max_length=100),
        ),
    ]
