# Generated by Django 2.0.6 on 2019-07-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrest', '0005_auto_20190725_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misura',
            name='Altezza_Peso',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='misura',
            name='Annotazioni',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='misura',
            name='Designazione_Lavori',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='misura',
            name='Larghezza',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='misura',
            name='Lunghezza',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='misura',
            name='Negativi',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='misura',
            name='Parti_Uguali',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='misura',
            name='Riserva',
            field=models.CharField(choices=[('NO', 'No'), ('Si', 'Si')], default='NO', max_length=10),
        ),
    ]
