# Generated by Django 2.0.6 on 2019-08-05 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartrest', '0009_lavoro_debito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soglia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Importo_Pagamento', models.FloatField()),
                ('Percentuale_Da_Raggiungere', models.FloatField()),
                ('Contratto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartrest.Contratto')),
            ],
        ),
    ]
