# Generated by Django 2.0.6 on 2019-08-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrest', '0011_lavoro_percentuale'),
    ]

    operations = [
        migrations.AddField(
            model_name='soglia',
            name='Attuale',
            field=models.BooleanField(default=True),
        ),
    ]
