# Generated by Django 2.0.6 on 2019-08-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrest', '0012_soglia_attuale'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratto',
            name='Terminato',
            field=models.BooleanField(default=False),
        ),
    ]
