# Generated by Django 2.0.6 on 2019-08-16 21:04

from django.db import migrations, models
import django.db.models.deletion
import smartrest.models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrest', '0013_contratto_terminato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giornale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField()),
                ('Meteo', models.CharField(max_length=150)),
                ('Annotazioni_Generali', models.TextField(max_length=2000)),
                ('Contratto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartrest.Contratto')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to=smartrest.models.Images.contract_directory_path, validators=[smartrest.models.Images.validate_file_extension, smartrest.models.Images.validate_file_size], verbose_name='Image')),
                ('Giornale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartrest.Giornale')),
            ],
        ),
    ]
