# Generated by Django 2.0.6 on 2019-08-20 07:07

from django.db import migrations, models
import smartrest.models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrest', '0015_auto_20190817_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Password_Block',
            field=models.CharField(default='smartcontract', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='Image',
            field=models.ImageField(upload_to=smartrest.models.Images.contract_directory_path, validators=[smartrest.models.Images.validate_file_extension, smartrest.models.Images.validate_file_size], verbose_name='Image'),
        ),
    ]
