# Generated by Django 2.0.6 on 2019-08-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrest', '0016_auto_20190820_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavoro',
            name='Aliquota',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
