# Generated by Django 2.0.6 on 2019-08-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrest', '0019_auto_20190824_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transazione',
            name='Descrizione',
            field=models.TextField(max_length=500),
        ),
    ]
