# Generated by Django 2.0.6 on 2019-08-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrest', '0020_auto_20190824_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='misura',
            name='Firma_Direttore',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='misura',
            name='Firma_Stazione',
            field=models.CharField(default='', max_length=200),
        ),
    ]
