# Generated by Django 2.0.6 on 2019-08-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrest', '0021_auto_20190825_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misura',
            name='Firma_Direttore',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='misura',
            name='Firma_Stazione',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
