# Generated by Django 2.0.6 on 2019-08-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrest', '0022_auto_20190825_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='giornale',
            name='Firma_Direttore',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
